language: node_js
node_js:
  - "8"
notifications:
  email: false
before_install:
# package-lock.json was introduced in npm@5
  - '[[ $(node -v) =~ ^v9.*$ ]] || npm install -g npm@latest' # skipped when using node 9
  - npm install -g greenkeeper-lockfile@1
before_script: greenkeeper-lockfile-update
script:
  - npm test && npm run integration
after_script: greenkeeper-lockfile-upload
